adminUser:
  password: vault:rom-cjxd11-2/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: rverduci@cloudbees.com
  token: vault:rom-cjxd11-2/pipelineUser:token
  username: core-platform-test-bot
prow:
  hmacToken: vault:rom-cjxd11-2/prow:hmacToken
